import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/sidebar";
import { QueryProvider } from "./components/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <div className="h-full flex">
          <SideBar />
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
